# Generated by Django 2.1.5 on 2019-01-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Posted on'),
        ),
    ]
